Creating authors list distinct from editors
w3c/rch-explainer pull request #10
Opened 2023-10-03 16:25 UTC by philarcher

Addresses @iherman's comment in Issue #9

2023-10-03 16:29 UTC, iherman approved these changes

2023-10-03 17:43 UTC, gkellogg approved these changes

2023-10-03 18:46 UTC, msporny requested changes
As flattered as I am for being listed as an author, I don't think I contributed much to this document, either as an author or an editor? I certainly don't remember writing any of it. It wouldn't be fair to Ivan and the other editors/authors, who did a ton of work on this, to list me. Please remove me from the Editor/Author sections; I don't deserve the credit here. :)

2023-10-04 09:20 UTC, philarcher commented
> As flattered as I am for being listed as an author, I don't think I contributed much to this document, either as an author or an editor? I certainly don't remember writing any of it. It wouldn't be fair to Ivan and the other editors/authors, who did a ton of work on this, to list me. Please remove me from the Editor/Author sections; I don't deserve the credit here. :)

With trepidation and reluctance, this has been done, Manu. 

If there are any names that should be acknowledged that are not currently so, then please speak up. Acknowledgement of effort is important.

2023-10-04 09:21 UTC, merged